image: Visual Studio 2019

configuration: Release

before_build:
  - dotnet restore

environment:
  MINVERBUILDMETADATA: build.%APPVEYOR_BUILD_NUMBER%

version: '{build}'

build:
  parallel: true
  verbosity: minimal

test_script:
  - dotnet test

artifacts:
  - path: src\Colourful\bin\%configuration%\*.nupkg
