image: Visual Studio 2017

configuration: Release

before_build:
  - dotnet restore

environment:
  base_version: '2.0.4'
  version_suffix: ''

version: $(base_version).{build}$(version_suffix)

dotnet_csproj:
  patch: true
  file: 'src\Colourful\*.csproj'
  version: '$(base_version)$(version_suffix)'
  assembly_version: '$(base_version)'
  file_version: '$(base_version).{build}'

build:
  parallel: true
  verbosity: minimal

test_script:
  - cd tests\Colourful.Tests
  - dotnet xunit --fx-version 2.0.0
  - cd ..\..

artifacts:
  - path: src\Colourful\bin\%configuration%\*.nupkg