image: Visual Studio 2019

configuration: Release

before_build:
  - dotnet restore

environment:
  base_version: '2.0.5'
  version_suffix: '-alpha7'

version: $(base_version).{build}$(version_suffix)

dotnet_csproj:
  patch: true
  file: 'src\Colourful\*.csproj'
  version: '$(base_version)$(version_suffix)'
  assembly_version: '$(base_version)'
  file_version: '$(base_version).{build}'

build:
  parallel: true
  verbosity: minimal

test_script:
  - dotnet test

artifacts:
  - path: src\Colourful\bin\%configuration%\*.nupkg
  - path: src\Colourful\bin\%configuration%\*.snupkg